name: RSpec CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: yama_meshi_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: password
      DATABASE_URL: "postgres://postgres:password@localhost:5432/yama_meshi_test"
      DISABLE_BOOTSNAP: true

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.9
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libpq-dev nodejs yarn

      - name: Prepare database
        run: |
          chmod +x bin/rails
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run RSpec
        run: |
          bundle exec rspec
